fix(avo-1866): adjust permissions
viaacode/avo2-proxy pull request #431
Opened 2022-05-09 08:22 UTC by ian-emsens-shd

https://meemoo.atlassian.net/browse/AVO-1866

2022-05-11 09:04 UTC, bertyhell requested changes

2022-05-11 09:04 UTC, bertyhell commented on server/src/modules/data/data.permissions.ts
> +			PermissionName.VIEW_USERS_IN_SAME_COMPANY
This is a security breach. Users with the permission VIEW_USERS_IN_SAME_COMPANY will still be able to see all the users.

The solution here would be to split the query into 2 queries:
* GET_USERS
* GET_USERS_IN_SAME_COMPANY

The GET_USERS_IN_SAME_COMPANY would look something like this:
```graphql
	query getUsers(
		$offset: Int!
		$limit: Int!
		$orderBy: [users_summary_view_order_by!]!
		$where: users_summary_view_bool_exp!
    $companyId: String!
	) {
		users_summary_view(offset: $offset, limit: $limit, order_by: $orderBy, where: {_and: [{company_id: {_eq: $companyId}}, $where]}) {
			user_id
			full_name
			first_name
			last_name
			mail
			last_access_at
			is_blocked
			blocked_at {
				date: max
			}
			unblocked_at {
				date: max
			}
			profile_id
			stamboek
			acc_created_at
			group_id
			group_name
			company_name
			is_exception
			business_category
			idps {
				idp
			}
			classifications {
				key
			}
			contexts {
				key
			}
			organisations {
				organization_id
				unit_id
				organization {
					ldap_description
				}
			}
			user {
				temp_access {
					until
					from
					current {
						status
					}
				}
			}
		}
		users_summary_view_aggregate(where: {_and: [{company_id: {_eq: $companyId}}, $where]}) {
			aggregate {
				count
			}
		}
	}
```

And in the proxy the permission check for this query would look like this:
```
	GET_USERS_IN_SAME_COMPANY: async (user: Avo.User.User, query: string, variables: any) => {
			if (AuthService.hasPermission(user, PermissionName.EDIT_ANY_USER)) {
				return true;
			}
			if (
				AuthService.hasPermission(user, PermissionName.VIEW_USERS_IN_SAME_COMPANY) &&
				variables.companyId === user.profile.company_id
			) {
				return true;
			}
			return false;
		},
```

2022-05-12 06:44 UTC, bertyhell requested changes

2022-05-12 06:44 UTC, bertyhell commented on server/src/modules/data/data.service.ts
> +	static transformVariablesByPermission(
don't create your own permission handling logic, use the standard way of checking permissions in: server/src/modules/data/data.permissions.ts


see remark: https://github.com/viaacode/avo2-proxy/pull/431/files#r870053492

2022-05-12 07:25 UTC, ian-emsens-shd commented on server/src/modules/data/data.service.ts
> +	static transformVariablesByPermission(
This isn't a permission check, this mutates the query based on which permissions the user does and does not have.

2022-05-12 07:51 UTC, bertyhell commented on server/src/modules/data/data.service.ts
> +	static transformVariablesByPermission(
It's cleaner to use 2 separate queries with their own permissions.
That way the permissions check happens in a predictable place just like all the other permission checks.

modifying the existing GET_USERS where object based on permissions doesn't follow the existing way of working.

I checked with Bart N. to get his opinion, he also thinks a separate query is more logical.

2022-05-12 08:15 UTC, ian-emsens-shd commented on server/src/modules/data/data.service.ts
> +	static transformVariablesByPermission(
I disagree but let's go with democracy

2022-05-12 11:20 UTC, bertyhell approved these changes

2022-05-16 07:38 UTC, merged