feat(avo-2138): create script to migrate descriptions to text blocks
viaacode/avo2-proxy pull request #487
Opened 2022-08-31 09:14 UTC by bertyhell

https://meemoo.atlassian.net/browse/AVO-2138

2022-08-31 09:21 UTC, bartnaessens approved these changes

2022-08-31 13:46 UTC, ian-emsens-shd requested changes

2022-08-31 13:46 UTC, ian-emsens-shd commented on server/scripts/migrate-assignments/migrate-assignment-descriptions.ts
> +	let offset = 0;
Voeg hier een script parameter toe en log de vooruitgang (bv. `Finished processing item #1234`, 1234 is dan de offset die we de volgende run meegeven) van het script zodat we eventuele failures makkelijk kunnen herstarten vanaf het punt waar ze faalde.

2022-09-01 18:15 UTC, ian-emsens-shd approved these changes

2022-09-06 08:12 UTC, merged