Feature/avo 2180
viaacode/avo2-proxy pull request #512
Opened 2022-10-06 14:20 UTC by ian-emsens-shd

https://meemoo.atlassian.net/browse/AVO-2180

2022-10-12 09:13 UTC, bertyhell requested changes

2022-10-12 09:13 UTC, bertyhell commented on server/src/modules/search/search.consts.ts
> +export const NUMBER_OF_FILTER_OPTIONS = 100000;
this worked correctly for teachers without increasing this number
so why do we need to increase it to fix it for pupils?

2022-10-12 16:28 UTC, ian-emsens-shd commented on server/src/modules/search/search.consts.ts
> +export const NUMBER_OF_FILTER_OPTIONS = 100000;
This fixes the below criteria in AVO-2180's description.

> Het lijkt er op dat als leerling er enkel binnen de eerste 40 reeksen gezocht wordt, ipv binnen de eerste 1000 (.?) zoals bij leerkrachten.

Before
![image](https://user-images.githubusercontent.com/90180417/195397889-d1ff5df4-2a9b-4113-98a6-0b2b33d0e688.png)


After
![image](https://user-images.githubusercontent.com/90180417/195397910-1cb93e31-d81c-4624-b579-7bd6e674b0b9.png)


This increases which series can be found in the modal as shown above using the term `Wereld`

2022-10-13 07:40 UTC, bertyhell commented on server/src/modules/search/search.consts.ts
> +export const NUMBER_OF_FILTER_OPTIONS = 100000;
You're not answering my question.
This works correctly for teachers on QAS:
![image](https://user-images.githubusercontent.com/1710840/195532515-48e875ad-58ec-44e0-abab-f1905072329e.png)

So why do we need to increase the number for pupils. You would think since it works for teachers, that you should be able to fix it for pupils as well without increasing this number?

2022-10-13 08:40 UTC, bertyhell approved these changes

2022-10-13 14:15 UTC, merged